In [1]:
import pandas as pd
import numpy as np

In [2]:
import re

In [3]:
from pandas.testing import assert_series_equal

In [19]:
acct = pd.read_csv('FEEDVISOR_pre_daily_collection_snapshot_cleaned_pai_snapshot_c1_d2019-01-01_account.csv', dtype=object)
trgt = pd.read_csv('FEEDVISOR_pre_daily_collection_snapshot_cleaned_pai_snapshot_c1_d2019-01-01_target.csv', dtype=object)

In [20]:
big_acct = pd.read_csv('FEEDVISOR_pre_daily_collection_snapshot_pre_stitch_cleaned_account_NEW2019-01-10.csv', dtype=object)
big_trgt = pd.read_csv('FEEDVISOR_new_pre_stitch_2019-01-09_pre_stitch_cleaned_target_with_profiling.csv', dtype=object)

In [21]:
assert (big_acct.index == big_trgt.index).all()
assert (acct.index == trgt.index).all()

In [22]:
big_acct.dropna(subset=['date'], inplace=True)
big_trgt.dropna(subset=['date'], inplace=True)
acct.dropna(subset=['date'], inplace=True)
trgt.dropna(subset=['date'], inplace=True)

big_acct.drop(big_acct[big_acct.date == '#NAME?'].index, inplace=True)
big_trgt.drop(big_trgt[big_trgt.date == '#NAME?'].index, inplace=True)

big_acct.drop(big_acct[big_acct.next_calculated_exit_point == 'Non Preventable BUT addressable'].index, inplace=True)

acct.next_calculated_exit_point = acct.next_calculated_exit_point.apply(lambda x: re.sub('-0', '-', x))

big_acct.churn_probability_date = big_acct.churn_probability_date.apply(
    lambda x: re.sub('^0', '', x) if pd.notnull(x) else x)

In [23]:
acct.churn_probability_date = pd.to_datetime(acct.churn_probability_date, format='%Y-%m-%d').astype(str)

big_acct.next_calculated_exit_point = pd.to_datetime(big_acct.next_calculated_exit_point, format='%Y-%m-%d').astype(str)

acct.next_calculated_exit_point = pd.to_datetime(acct.next_calculated_exit_point, format='%Y-%m-%d').astype(str)

In [24]:
big_acct.date = big_acct.date.str.lstrip('SDR,')
big_acct.date = big_acct.date.str.rstrip('",')
big_trgt.date = big_trgt.date.str.lstrip('SDR,')
big_trgt.date = big_trgt.date.str.rstrip('",')

In [25]:
big_acct.cancellation_reason = big_acct.cancellation_reason.str.lstrip('"')
big_acct.cancellation_reason = big_acct.cancellation_reason.str.rstrip('"')

In [26]:
big_acct.churn_probability_date = pd.to_datetime(big_acct.churn_probability_date, format='%m/%d/%Y').astype(str)
acct.date = pd.to_datetime(acct.date, format='%Y-%m-%d').astype(str)
trgt.date = pd.to_datetime(trgt.date, format='%Y-%m-%d').astype(str)
big_acct.date = pd.to_datetime(big_acct.date, format='%Y-%m-%d').astype(str)
big_trgt.date = pd.to_datetime(big_trgt.date, format='%Y-%m-%d').astype(str)

In [27]:
# preprocessing!
trgt.churn_in_stage = trgt.churn_in_stage.astype(float)
trgt.churn_in_stage_paying = trgt.churn_in_stage_paying.astype(int)
trgt.churn_in_stage_poc = trgt.churn_in_stage_poc.astype(float)
trgt.reached_poc_stage = trgt.reached_poc_stage.astype(int)
trgt.repricing_activated = trgt.repricing_activated.astype(int)
trgt.pai_is_deleted = trgt.pai_is_deleted.astype(int)
trgt.account_birth_date = pd.to_datetime(trgt.account_birth_date, format='%Y-%m-%d').astype(str)
big_trgt.account_birth_date = pd.to_datetime(big_trgt.account_birth_date, format='%Y-%m-%d').astype(str)
trgt.churn_month = pd.to_datetime(trgt.churn_month, format='%Y-%m-%d').astype(str)
big_trgt.churn_month = pd.to_datetime(big_trgt.churn_month, format='%Y-%m-%d').astype(str)
trgt.last_activity = pd.to_datetime(trgt.last_activity, format='%Y-%m-%d').astype(str)
big_trgt.last_activity = pd.to_datetime(big_trgt.last_activity, format='%Y-%m-%d').astype(str)
trgt.poc_end_date = pd.to_datetime(trgt.poc_end_date, format='%Y-%m-%d').astype(str)
big_trgt.poc_end_date = pd.to_datetime(big_trgt.poc_end_date, format='%Y-%m-%d').astype(str)

In [28]:
for col in ['account_currency_code', 'base_mrr', 'last_bill_total_fee', 'last_bill_variable_fee', 
 'of_repricing_online_stores']:
    acct[col] = acct[col].astype(float)

In [36]:
for col in ['account_currency_code', 'base_mrr', 'last_bill_total_fee', 'last_bill_variable_fee', 
 'of_repricing_online_stores']:
    big_acct[col] = big_acct[col].astype(float)

In [29]:
acct.contract_term = acct.contract_term.apply(lambda x: str(float(x)) if not pd.isnull(float(x)) else x)

In [30]:
big_acct.contract_term = big_acct.contract_term.astype(str)

In [31]:
acct.contract_term = acct.contract_term.apply(lambda x: str(int(float(x))) if not pd.isnull(float(x)) else x)

In [32]:
big_acct.contract_term = big_acct.contract_term.astype(str)

In [33]:
acct.country = acct.country.map({'"Korea, Republic of"':'Korea, Republic of',
                  """\"Korea, Democratic People's Republic of\"""": "Korea, Democratic People's Republic of"})

In [57]:
# testing the groupby
t = pd.DataFrame(trgt.groupby('date')['last_activity'].apply(lambda x: x.mode())).reset_index()
t[t.level_1 != 0]

In [52]:
acct.set_index(['pai_account_id', 'date'], inplace=True)
trgt.set_index(['pai_account_id', 'date'], inplace=True)
big_acct.set_index(['pai_account_id', 'date'], inplace=True)
big_trgt.set_index(['pai_account_id', 'date'], inplace=True)

## Comparison
### Account

In [53]:
spare_cols = ['client_id','recipe_execution_date']
t1 = acct[sorted(list(acct))].drop(columns=spare_cols)
t2 = big_acct[sorted(list(set(list(big_acct)) & set(list(acct))))].drop(columns=spare_cols)
joint = t1.join(t2, how='inner', rsuffix='_big')

In [51]:
list(joint)

['account_currency_code',
 'account_name',
 'base_mrr',
 'cancellation_reason',
 'churn_preventability',
 'churn_probability',
 'churn_probability_date',
 'churn_probability_description',
 'contract_term',
 'country',
 'current_csm',
 'date',
 'email',
 'last_bill_total_fee',
 'last_bill_variable_fee',
 'next_calculated_exit_point',
 'of_repricing_online_stores',
 'package',
 'pai_account_id',
 'price_trend',
 'profit_trend',
 'time_zone',
 'totango_account_health',
 'upsell_opportunity_package',
 'account_currency_code_big',
 'account_name_big',
 'base_mrr_big',
 'cancellation_reason_big',
 'churn_preventability_big',
 'churn_probability_big',
 'churn_probability_date_big',
 'churn_probability_description_big',
 'contract_term_big',
 'country_big',
 'current_csm_big',
 'date_big',
 'email_big',
 'last_bill_total_fee_big',
 'last_bill_variable_fee_big',
 'next_calculated_exit_point_big',
 'of_repricing_online_stores_big',
 'package_big',
 'pai_account_id_big',
 'price_trend_big',
 'profit_trend_big',
 'time_zone_big',
 'totango_account_health_big',
 'upsell_opportunity_package_big']

In [54]:
n = int(joint.shape[1] / 2)
col_names = list(joint)
for (i,j) in (zip(range(n), range(n, 2 * n))):
    try:
        assert_series_equal(joint.iloc[:,i], joint.iloc[:,j], check_names=False, check_less_precise=True)
    except AssertionError as e:
        print('Prob in col {}, {}!'.format(col_names[i], col_names[j]), str(e)[:62])

Prob in col cancellation_reason, cancellation_reason_big! Series are different

Series values are different (1.83164 %)

Prob in col churn_probability_description, churn_probability_description_big! Series are different

Series values are different (7.11943 %)

Prob in col contract_term, contract_term_big! Series are different

Series values are different (0.66361 %)

Prob in col country, country_big! Series are different

Series values are different (97.44145 %)

In [58]:
joint[joint.country != joint.country_big][['country', 'country_big']].dropna()

Empty DataFrame
Columns: [country, country_big]
Index: []

In [59]:
print('old_account {} rows, new_account {} rows, intersection is {}'.format(
    acct.shape[0], big_acct.shape[0], joint.shape[0]))

old_account 68767 rows, new_account 607396 rows, intersection is 52139

### Target

In [25]:
trgt = trgt.drop(columns='is_deleted')

In [26]:
spare_cols = ['client_id','recipe_execution_date']
u1 = trgt[sorted(list(trgt))].drop(columns=spare_cols)
u2 = big_trgt[sorted(list(set(list(big_trgt)) & set(list(trgt))))].drop(columns=spare_cols)
joint = u1.join(u2, how='inner', rsuffix='_new')

In [27]:
print('old_target {} rows, new_target {} rows, intersection is {}'.format(
    trgt.shape[0], big_trgt.shape[0], joint.shape[0]))

old_target 68767 rows, new_target 607397 rows, intersection is 52139

In [28]:
joint = joint[joint.pai_is_deleted_new == 0]

In [39]:
n = int(joint.shape[1] / 2)
col_names = list(joint)
for (i,j) in (zip(range(n), range(n, 2 * n))):
    try:
        assert_series_equal(joint.iloc[:,i], joint.iloc[:,j], check_names=False, check_dtype=False)
    except AssertionError as e:
        print('Prob in col {}!'.format(col_names[i]), e)

In [30]:
diff_cols = ['churn_in_stage', 'churn_in_stage_paying', 'churn_in_stage_poc', 'poc_end_date', 'stage']
diff_big = [x + '_new' for x in diff_cols]
diff_big_and_small = diff_cols + diff_big

churn_in_stage

In [233]:
trgt.loc[('001b000000FnoxB', '2017-10-08'),:]

client_id                         1
recipe_execution_date    2018-03-18
last_activity            2016-08-07
churn_month              2016-07-01
repricing_activated               0
profile                         smb
poc_end_date             2016-07-14
churn_in_stage_poc                0
reached_poc_stage                 1
stage                           poc
churn_in_stage_paying             0
churn_in_stage                    0
account_birth_date       2016-03-31
pai_is_deleted                    0
Name: (001b000000FnoxB, 2017-10-08), dtype: object

In [31]:
cols = ['churn_in_stage','churn_in_stage_new', 'stage', 'stage_new', 'reached_poc_stage', 'reached_poc_stage_new']
t = joint[joint['churn_in_stage'] != joint['churn_in_stage_new']].dropna(
    subset=['churn_in_stage','churn_in_stage_new'])[cols]
t.columns = cols
t.to_csv('old_vs_new_churn.csv')

In [32]:
t

Empty DataFrame
Columns: [churn_in_stage, churn_in_stage_new, stage, stage_new, reached_poc_stage, reached_poc_stage_new]
Index: []

In [33]:
t = joint[joint['stage'] != joint['stage_new']][diff_big_and_small].dropna(
        subset=['stage','stage_new'])[['churn_in_stage','churn_in_stage_new', 'stage','stage_new']]
t.columns = ['churn_in_stage_old','churn_in_stage_new', 'stage_old','stage_new']
t.to_csv('old_vs_new.csv')

In [35]:
t = joint[joint['poc_end_date'] != joint['poc_end_date_new']][diff_big_and_small].dropna(
        subset=['poc_end_date','poc_end_date_new'])[['churn_in_stage','churn_in_stage_new', 'poc_end_date', 'poc_end_date_new']]
t.columns = ['churn_in_stage_old','churn_in_stage_new', 'poc_end_date_old','poc_end_date_new']
# t.to_csv('old_vs_new_poc_end_date.csv')

In [36]:
t

Empty DataFrame
Columns: [churn_in_stage_old, churn_in_stage_new, poc_end_date_old, poc_end_date_new]
Index: []

In [209]:
joint[joint['churn_in_stage_paying'] != joint['churn_in_stage_paying_big']][diff_big_and_small]

                            churn_in_stage  churn_in_stage_paying  \
pai_account_id  date
001b000000HD2rh 2017-11-07             0.0                      0
                2017-11-13             0.0                      0
001b0000019wSsQ 2017-12-09             0.0                      0
001b0000019wf5M 2017-12-09             0.0                      0
001b0000019wfNp 2017-12-09             0.0                      0
001b000001Eh9R9 2017-12-09             0.0                      0
001b000001Eh9qL 2017-12-09             0.0                      0

                            churn_in_stage_poc poc_end_date stage  \
pai_account_id  date
001b000000HD2rh 2017-11-07                 0.0   2015-09-04   poc
                2017-11-13                 0.0   2015-09-04   poc
001b0000019wSsQ 2017-12-09                 0.0   2016-03-30   poc
001b0000019wf5M 2017-12-09                 0.0   2015-12-07   poc
001b0000019wfNp 2017-12-09                 0.0   2015-11-27   poc
001b000001Eh9R9 2017-12-09                 0.0   2015-12-07   poc
001b000001Eh9qL 2017-12-09                 0.0   2015-12-17   poc

                            churn_in_stage_big  churn_in_stage_paying_big  \
pai_account_id  date
001b000000HD2rh 2017-11-07                 1.0                          1
                2017-11-13                 1.0                          1
001b0000019wSsQ 2017-12-09                 1.0                          1
001b0000019wf5M 2017-12-09                 1.0                          1
001b0000019wfNp 2017-12-09                 1.0                          1
001b000001Eh9R9 2017-12-09                 1.0                          1
001b000001Eh9qL 2017-12-09                 1.0                          1

                            churn_in_stage_poc_big poc_end_date_big stage_big
pai_account_id  date
001b000000HD2rh 2017-11-07                     NaN       2015-09-04    paying
                2017-11-13                     NaN       2015-09-04    paying
001b0000019wSsQ 2017-12-09                     NaN       2016-03-30    paying
001b0000019wf5M 2017-12-09                     NaN       2015-12-07    paying
001b0000019wfNp 2017-12-09                     NaN       2015-11-27    paying
001b000001Eh9R9 2017-12-09                     NaN       2015-12-07    paying
001b000001Eh9qL 2017-12-09                     NaN       2015-12-17    paying

stage

In [220]:
joint[joint['stage'] != joint['stage_big']][diff_big_and_small]

                            churn_in_stage  churn_in_stage_paying  \
pai_account_id  date
001b000000HD2rh 2017-11-07             0.0                      0
                2017-11-13             0.0                      0
001b0000019wSsQ 2017-12-09             0.0                      0
001b0000019wf5M 2017-12-09             0.0                      0
001b0000019wfNp 2017-12-09             0.0                      0
001b000001Eh9R9 2017-12-09             0.0                      0
001b000001Eh9qL 2017-12-09             0.0                      0

                            churn_in_stage_poc poc_end_date stage  \
pai_account_id  date
001b000000HD2rh 2017-11-07                 0.0   2015-09-04   poc
                2017-11-13                 0.0   2015-09-04   poc
001b0000019wSsQ 2017-12-09                 0.0   2016-03-30   poc
001b0000019wf5M 2017-12-09                 0.0   2015-12-07   poc
001b0000019wfNp 2017-12-09                 0.0   2015-11-27   poc
001b000001Eh9R9 2017-12-09                 0.0   2015-12-07   poc
001b000001Eh9qL 2017-12-09                 0.0   2015-12-17   poc

                            churn_in_stage_big  churn_in_stage_paying_big  \
pai_account_id  date
001b000000HD2rh 2017-11-07                 1.0                          1
                2017-11-13                 1.0                          1
001b0000019wSsQ 2017-12-09                 1.0                          1
001b0000019wf5M 2017-12-09                 1.0                          1
001b0000019wfNp 2017-12-09                 1.0                          1
001b000001Eh9R9 2017-12-09                 1.0                          1
001b000001Eh9qL 2017-12-09                 1.0                          1

                            churn_in_stage_poc_big poc_end_date_big stage_big
pai_account_id  date
001b000000HD2rh 2017-11-07                     NaN       2015-09-04    paying
                2017-11-13                     NaN       2015-09-04    paying
001b0000019wSsQ 2017-12-09                     NaN       2016-03-30    paying
001b0000019wf5M 2017-12-09                     NaN       2015-12-07    paying
001b0000019wfNp 2017-12-09                     NaN       2015-11-27    paying
001b000001Eh9R9 2017-12-09                     NaN       2015-12-07    paying
001b000001Eh9qL 2017-12-09                     NaN       2015-12-17    paying

churn_in_stage/churn_in_stage_poc

In [213]:
joint[joint[diff_cols[0]] != joint[diff_cols[0] + '_big']].dropna()[diff_big_and_small]

                            churn_in_stage  churn_in_stage_paying  \
pai_account_id  date
001b000000FnoxB 2017-10-08             0.0                      0
                2017-10-09             0.0                      0
                2017-10-11             0.0                      0
                2017-10-12             0.0                      0
                2017-10-15             0.0                      0
                2017-10-16             0.0                      0
                2017-10-17             0.0                      0
001b000003EgXAM 2017-12-09             0.0                      0
001b000003EjIPW 2017-12-09             0.0                      0
001b000003GZC8g 2017-12-09             0.0                      0
001b000003NHFmc 2017-12-28             1.0                      0
                2017-12-29             1.0                      0
                2018-01-03             1.0                      0
                2018-01-05             1.0                      0
                2018-01-06             1.0                      0
                2018-01-08             1.0                      0
                2018-01-10             1.0                      0
                2018-01-11             1.0                      0
001b000003eO6v4 2017-12-09             0.0                      0
001b000003j7Rcs 2017-11-04             0.0                      0
                2017-11-05             0.0                      0
                2017-11-07             0.0                      0
001b000003jzAIz 2017-10-17             0.0                      0

                            churn_in_stage_poc poc_end_date stage  \
pai_account_id  date
001b000000FnoxB 2017-10-08                 0.0   2016-07-14   poc
                2017-10-09                 0.0   2016-07-14   poc
                2017-10-11                 0.0   2016-07-14   poc
                2017-10-12                 0.0   2016-07-14   poc
                2017-10-15                 0.0   2016-07-14   poc
                2017-10-16                 0.0   2016-07-14   poc
                2017-10-17                 0.0   2016-07-14   poc
001b000003EgXAM 2017-12-09                 0.0   2016-07-06   poc
001b000003EjIPW 2017-12-09                 0.0   2016-04-15   poc
001b000003GZC8g 2017-12-09                 0.0   2016-04-14   poc
001b000003NHFmc 2017-12-28                 1.0   2016-08-15   poc
                2017-12-29                 1.0   2016-08-15   poc
                2018-01-03                 1.0   2016-08-15   poc
                2018-01-05                 1.0   2016-08-15   poc
                2018-01-06                 1.0   2016-08-15   poc
                2018-01-08                 1.0   2016-08-15   poc
                2018-01-10                 1.0   2016-08-15   poc
                2018-01-11                 1.0   2016-08-15   poc
001b000003eO6v4 2017-12-09                 0.0   2017-05-09   poc
001b000003j7Rcs 2017-11-04                 0.0   2017-09-08   poc
                2017-11-05                 0.0   2017-09-08   poc
                2017-11-07                 0.0   2017-09-08   poc
001b000003jzAIz 2017-10-17                 0.0   2017-08-31   poc

                            churn_in_stage_big  churn_in_stage_paying_big  \
pai_account_id  date
001b000000FnoxB 2017-10-08                 1.0                          0
                2017-10-09                 1.0                          0
                2017-10-11                 1.0                          0
                2017-10-12                 1.0                          0
                2017-10-15                 1.0                          0
                2017-10-16                 1.0                          0
                2017-10-17                 1.0                          0
001b000003EgXAM 2017-12-09                 1.0                          0
001b000003EjIPW 2017-12-09                 1.0                          0
001b000003GZC8g 2017-12-09                 1.0                          0
001b000003NHFmc 2017-12-28                 0.0                          0
                2017-12-29                 0.0                          0
                2018-01-03                 0.0                          0
                2018-01-05                 0.0                          0
                2018-01-06                 0.0                          0
                2018-01-08                 0.0                          0
                2018-01-10                 0.0                          0
                2018-01-11                 0.0                          0
001b000003eO6v4 2017-12-09                 1.0                          0
001b000003j7Rcs 2017-11-04                 1.0                          0
                2017-11-05                 1.0                          0
                2017-11-07                 1.0                          0
001b000003jzAIz 2017-10-17                 1.0                          0

                            churn_in_stage_poc_big poc_end_date_big stage_big
pai_account_id  date
001b000000FnoxB 2017-10-08                     1.0       2016-07-14       poc
                2017-10-09                     1.0       2016-07-14       poc
                2017-10-11                     1.0       2016-07-14       poc
                2017-10-12                     1.0       2016-07-14       poc
                2017-10-15                     1.0       2016-07-14       poc
                2017-10-16                     1.0       2016-07-14       poc
                2017-10-17                     1.0       2016-07-14       poc
001b000003EgXAM 2017-12-09                     1.0       2016-07-06       poc
001b000003EjIPW 2017-12-09                     1.0       2016-04-15       poc
001b000003GZC8g 2017-12-09                     1.0       2016-04-14       poc
001b000003NHFmc 2017-12-28                     0.0       2016-08-15       poc
                2017-12-29                     0.0       2016-08-15       poc
                2018-01-03                     0.0       2016-08-15       poc
                2018-01-05                     0.0       2016-08-15       poc
                2018-01-06                     0.0       2016-08-15       poc
                2018-01-08                     0.0       2016-08-15       poc
                2018-01-10                     0.0       2016-08-15       poc
                2018-01-11                     0.0       2016-08-15       poc
001b000003eO6v4 2017-12-09                     1.0       2017-05-09       poc
001b000003j7Rcs 2017-11-04                     1.0       2017-09-08       poc
                2017-11-05                     1.0       2017-09-08       poc
                2017-11-07                     1.0       2017-09-08       poc
001b000003jzAIz 2017-10-17                     1.0       2017-08-31       poc

poc_end_date

In [71]:
joint[joint['poc_end_date'] != joint['poc_end_date_new']]['poc_end_date', 'poc_end_date_new']

KeyError: ('poc_end_date', 'poc_end_date_new')

In [243]:
set(trgt.id.values) - set(acct.id.values)

AttributeError: 'DataFrame' object has no attribute 'id'

In [245]:
acct.reset_index(inplace=True)
big_acct.reset_index(inplace=True)
trgt.reset_index(inplace=True)
big_trgt.reset_index(inplace=True)

In [246]:
acct['id'] = acct['pai_account_id'] + acct['date'].astype(str)
trgt['id'] = trgt['pai_account_id'] + trgt['date'].astype(str)

big_acct['id'] = big_acct['pai_account_id'] + big_acct['date'].astype(str)
big_trgt['id'] = big_trgt['pai_account_id'] + big_trgt['date'].astype(str)

In [247]:
set(big_acct.id.values) - set(big_trgt.id.values)

set()

In [248]:
set(acct.id.values) - set(trgt.id.values)

set()

In [249]:
set(big_trgt.id.values) - set(big_acct.id.values)

set()

In [250]:
set(trgt.id.values) - set(acct.id.values)

set()

In [253]:
len(set(trgt.id.values) - set(big_trgt.id.values))

18252

In [25]:
new_less_old = set(big_trgt.loc[big_trgt.pai_is_deleted == '0'].id.values) - set(trgt.id.values)

In [26]:
len(new_less_old)

75838

In [258]:
trgt.loc[trgt.index.difference(big_trgt.index)].reset_index().groupby('date').nunique()

,pai_account_id,date,client_id,recipe_execution_date,last_activity,churn_month,repricing_activated,profile,poc_end_date,churn_in_stage_poc,reached_poc_stage,stage,churn_in_stage_paying,churn_in_stage,account_birth_date,pai_is_deleted,id
date,,,,,,,,,,,,,,,,,
2017-03-19,519,1,1,1,189,20,2,2,307,2,2,3,2,2,289,1,519
2017-04-16,549,1,1,1,197,25,2,2,321,2,2,3,2,2,302,1,549
2017-04-25,556,1,1,1,202,27,2,2,330,2,2,3,2,2,308,1,556
2017-10-04,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-10-05,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-10-08,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-10-09,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-10-11,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-10-12,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-10-15,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-10-16,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-10-17,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-10-18,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-10-22,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-10-24,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-10-25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-11-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-11-04,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-11-05,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-11-07,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-11-08,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-11-09,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-11-10,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-11-13,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-11-15,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-11-16,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-11-17,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-11-18,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-11-19,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-11-20,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-12-16,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-12-18,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-12-21,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-12-22,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-12-24,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2017-12-25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2018-02-10,689,1,1,1,215,90,2,2,421,2,2,3,2,2,400,1,689
2018-02-11,689,1,1,1,215,90,2,2,421,2,2,3,2,2,400,1,689
2018-02-12,689,1,1,1,215,90,2,2,421,2,2,3,2,2,400,1,689
2018-02-13,689,1,1,1,207,90,2,2,421,2,2,3,2,2,400,1,689
2018-02-14,689,1,1,1,209,90,2,2,421,2,2,3,2,2,400,1,689
2018-02-17,689,1,1,1,211,92,2,2,421,2,2,3,2,2,400,1,689
2018-02-18,690,1,1,1,211,92,2,2,422,2,2,3,2,2,401,1,690
2018-02-20,690,1,1,1,212,92,2,2,422,2,2,3,2,2,401,1,690
2018-02-21,690,1,1,1,211,92,2,2,422,2,2,3,2,2,401,1,690
2018-02-25,690,1,1,1,212,92,2,2,423,2,2,3,2,2,402,1,690
2018-02-26,690,1,1,1,213,92,2,2,423,2,2,3,2,2,402,1,690
2018-02-27,690,1,1,1,215,92,2,2,423,2,2,3,2,2,402,1,690
2018-02-28,690,1,1,1,217,94,2,2,423,2,2,3,2,2,402,1,690
2018-03-01,690,1,1,1,216,96,2,2,423,2,2,3,2,2,402,1,690
2018-03-02,690,1,1,1,216,96,2,2,423,2,2,3,2,2,402,1,690
2018-03-03,690,1,1,1,217,96,2,2,423,2,2,3,2,2,402,1,690
2018-03-05,690,1,1,1,217,96,2,2,423,2,2,3,2,2,402,1,690
2018-03-06,691,1,1,1,218,96,2,2,424,2,2,3,2,2,403,1,691
2018-03-07,692,1,1,1,219,96,2,2,425,2,2,3,2,2,404,1,692
2018-03-08,694,1,1,1,219,96,2,2,426,2,2,3,2,2,405,1,694
2018-03-09,694,1,1,1,218,96,2,2,426,2,2,3,2,2,405,1,694
2018-03-10,694,1,1,1,218,97,2,2,426,2,2,3,2,2,405,1,694
2018-03-16,694,1,1,1,222,97,2,2,426,2,2,3,2,2,405,1,694
2018-03-20,694,1,1,1,224,98,2,2,426,2,2,3,2,2,405,1,694

In [27]:
new_old_intersection = set(big_trgt.id.values) & set(trgt.id.values)

In [28]:
len(new_old_intersection)

50507

In [29]:
len(new_less_old) + len(new_old_intersection)

126345

In [30]:
old_less_new = set(trgt.id.values) - set(big_trgt.id.values)

In [31]:
len(old_less_new)

18260

In [32]:
x = trgt[trgt.id.isin(list(old_less_new))].reset_index().groupby('date').count()

In [33]:
x[x.pai_account_id > 1].sort_index()

,pai_account_id,client_id,recipe_execution_date,last_activity,churn_month,repricing_activated,profile,poc_end_date,churn_in_stage_poc,reached_poc_stage,stage,churn_in_stage_paying,churn_in_stage,account_birth_date,is_deleted,pai_is_deleted,id
date,,,,,,,,,,,,,,,,,
2017-03-19,519,519,519,519,272,519,517,519,407,519,519,519,516,519,519,519,519
2017-04-16,549,549,549,548,284,549,548,549,436,549,549,549,548,549,549,549,549
2017-04-25,556,556,556,555,288,556,555,556,443,556,556,556,554,556,556,556,556
2018-02-10,689,689,689,688,386,689,687,689,577,689,689,689,688,689,689,689,689
2018-02-11,689,689,689,688,386,689,687,689,577,689,689,689,688,689,689,689,689
2018-02-12,689,689,689,688,386,689,687,689,577,689,689,689,688,689,689,689,689
2018-02-13,689,689,689,688,386,689,687,689,577,689,689,689,688,689,689,689,689
2018-02-14,689,689,689,688,386,689,687,689,577,689,689,689,688,689,689,689,689
2018-02-17,689,689,689,688,388,689,687,689,577,689,689,689,688,689,689,689,689
2018-02-18,690,690,690,689,388,690,688,690,578,690,690,690,689,690,690,690,690
2018-02-20,690,690,690,689,388,690,688,690,578,690,690,690,689,690,690,690,690
2018-02-21,690,690,690,689,388,690,689,690,578,690,690,690,689,690,690,690,690
2018-02-25,690,690,690,689,387,690,689,690,578,690,690,690,689,690,690,690,690
2018-02-26,690,690,690,689,387,690,689,690,578,690,690,690,689,690,690,690,690
2018-02-27,690,690,690,689,387,690,689,690,578,690,690,690,689,690,690,690,690
2018-02-28,690,690,690,689,390,690,689,690,578,690,690,690,689,690,690,690,690
2018-03-01,690,690,690,689,393,690,689,690,578,690,690,690,689,690,690,690,690
2018-03-02,690,690,690,689,394,690,689,690,578,690,690,690,689,690,690,690,690
2018-03-03,690,690,690,689,394,690,689,690,578,690,690,690,689,690,690,690,690
2018-03-05,690,690,690,689,394,690,689,690,578,690,690,690,689,690,690,690,690
2018-03-06,691,691,691,690,394,691,690,691,579,691,691,691,690,691,691,691,691
2018-03-07,692,692,692,691,394,692,691,692,580,692,692,692,690,692,692,692,692
2018-03-08,694,694,694,693,394,694,693,694,582,694,694,694,692,694,694,694,694
2018-03-09,694,694,694,693,394,694,693,694,582,694,694,694,692,694,694,694,694
2018-03-10,694,694,694,693,395,694,693,694,582,694,694,694,692,694,694,694,694
2018-03-16,694,694,694,693,395,694,693,694,582,694,694,694,692,694,694,694,694
2018-03-20,694,694,694,693,396,694,693,694,582,694,694,694,693,694,694,694,694

In [87]:
dates_to_check = x[x.pai_account_id == 1].index.tolist()

In [96]:
trgt.xs(dates_to_check[0], level=1).head()

,client_id,recipe_execution_date,last_activity,churn_month,repricing_activated,profile,poc_end_date,churn_in_stage_poc,reached_poc_stage,stage,churn_in_stage_paying,churn_in_stage,account_birth_date,is_deleted,pai_is_deleted,id
pai_account_id,,,,,,,,,,,,,,,,
001b000003EgQai,1,2018-03-18,2017-10-2,NaN,1,smb,2016-5-1,0.0,1,paying,0,0.0,2016-1-31,false,0,001b000003EgQai2017-10-04
001b000001Eh9qL,1,2018-03-18,2016-8-18,2016-8-1,0,smb,2015-12-17,NaN,1,paying,1,1.0,2015-9-17,false,0,001b000001Eh9qL2017-10-04
001b000003EgXAM,1,2018-03-18,2016-8-10,2016-8-1,0,smb,2016-7-6,1.0,1,poc,0,1.0,2016-4-6,false,0,001b000003EgXAM2017-10-04
001b000001EhBMH,1,2018-03-18,2017-9-12,NaN,1,enterprise,2016-3-30,0.0,0,paying,0,0.0,2016-3-29,false,0,001b000001EhBMH2017-10-04
001b000003ODOhK,1,2018-03-18,2017-8-21,2016-9-1,0,smb,2016-8-30,1.0,1,poc,0,1.0,2016-5-30,false,0,001b000003ODOhK2017-10-04

In [104]:
issues = {}
for date in dates_to_check:
    old = set(trgt.xs(dates_to_check[0], level=1).index)
    new = set(big_trgt.xs(dates_to_check[0], level=1).index)
    issues[date] = old - new

In [94]:
trgt.loc(axis=0)[:,dates_to_check[0]]

,,client_id,recipe_execution_date,last_activity,churn_month,repricing_activated,profile,poc_end_date,churn_in_stage_poc,reached_poc_stage,stage,churn_in_stage_paying,churn_in_stage,account_birth_date,is_deleted,pai_is_deleted,id
pai_account_id,date,,,,,,,,,,,,,,,,
001b000003EgQai,2017-10-04,1,2018-03-18,2017-10-2,NaN,1,smb,2016-5-1,0.0,1,paying,0,0.0,2016-1-31,false,0,001b000003EgQai2017-10-04
001b000001Eh9qL,2017-10-04,1,2018-03-18,2016-8-18,2016-8-1,0,smb,2015-12-17,NaN,1,paying,1,1.0,2015-9-17,false,0,001b000001Eh9qL2017-10-04
001b000003EgXAM,2017-10-04,1,2018-03-18,2016-8-10,2016-8-1,0,smb,2016-7-6,1.0,1,poc,0,1.0,2016-4-6,false,0,001b000003EgXAM2017-10-04
001b000001EhBMH,2017-10-04,1,2018-03-18,2017-9-12,NaN,1,enterprise,2016-3-30,0.0,0,paying,0,0.0,2016-3-29,false,0,001b000001EhBMH2017-10-04
001b000003ODOhK,2017-10-04,1,2018-03-18,2017-8-21,2016-9-1,0,smb,2016-8-30,1.0,1,poc,0,1.0,2016-5-30,false,0,001b000003ODOhK2017-10-04
001b000003jw5h0,2017-10-04,1,2018-03-18,2017-7-30,2017-9-29,0,smb,2017-3-29,0.0,0,paying,1,1.0,2017-3-28,false,0,001b000003jw5h02017-10-04
001b000003EjIPW,2017-10-04,1,2018-03-18,2017-10-2,2016-5-1,0,smb,2016-4-15,1.0,1,poc,0,1.0,2016-1-15,false,0,001b000003EjIPW2017-10-04
001b000003GZ2GR,2017-10-04,1,2018-03-18,2017-9-20,NaN,1,smb,2016-4-30,0.0,1,paying,0,0.0,2016-1-18,false,0,001b000003GZ2GR2017-10-04
001b000003ODP7X,2017-10-04,1,2018-03-18,2017-9-26,2016-9-1,0,enterprise,2016-8-31,1.0,1,poc,0,1.0,2016-5-31,false,0,001b000003ODP7X2017-10-04
001b000003GZC8g,2017-10-04,1,2018-03-18,2017-8-8,2016-4-1,0,smb,2016-4-14,1.0,1,poc,0,1.0,2016-1-14,false,0,001b000003GZC8g2017-10-04
001b000001EhSr1,2017-10-04,1,2018-03-18,2017-10-4,NaN,1,enterprise,2015-9-1,0.0,0,paying,0,0.0,2015-8-31,false,0,001b000001EhSr12017-10-04
001b000003ODaMP,2017-10-04,1,2018-03-18,2017-9-28,2016-12-1,0,smb,2016-8-31,1.0,1,poc,0,1.0,2016-5-31,false,0,001b000003ODaMP2017-10-04
001b000003uAHaW,2017-10-04,1,2018-03-18,2017-10-4,NaN,1,enterprise,2017-7-14,0.0,0,paying,0,0.0,2017-7-11,false,0,001b000003uAHaW2017-10-04
001b000003GaPwF,2017-10-04,1,2018-03-18,2017-9-13,NaN,1,smb,2016-4-15,0.0,1,paying,0,0.0,2016-1-15,false,0,001b000003GaPwF2017-10-04
001b000001EhU5G,2017-10-04,1,2018-03-18,2016-2-11,2016-2-1,0,smb,2015-12-07,NaN,1,paying,1,1.0,2015-9-7,false,0,001b000001EhU5G2017-10-04
001b000003ODbip,2017-10-04,1,2018-03-18,2017-8-3,2016-10-1,0,enterprise,2016-8-30,1.0,1,poc,0,1.0,2016-5-30,false,0,001b000003ODbip2017-10-04
001b000003H03h3,2017-10-04,1,2018-03-18,2017-4-25,2017-5-1,0,smb,2016-1-19,0.0,0,paying,1,1.0,2016-1-18,false,0,001b000003H03h32017-10-04
001b000003lKl1Q,2017-10-04,1,2018-03-18,2017-9-28,2017-9-18,0,smb,2017-9-18,1.0,1,poc,0,1.0,2017-6-16,false,0,001b000003lKl1Q2017-10-04
001b000001EhVno,2017-10-04,1,2018-03-18,2017-2-1,2017-2-1,0,smb,2015-8-29,0.0,0,paying,1,1.0,2015-8-28,false,0,001b000001EhVno2017-10-04
001b000003jzUgI,2017-10-04,1,2018-03-18,2017-8-14,2017-8-18,0,smb,2017-8-18,1.0,1,poc,0,1.0,2017-3-29,false,0,001b000003jzUgI2017-10-04
001b000003Md62a,2017-10-04,1,2018-03-18,2017-10-2,NaN,1,enterprise,2017-5-6,0.0,1,paying,0,0.0,2017-2-6,false,0,001b000003Md62a2017-10-04
001b000003Md62f,2017-10-04,1,2018-03-18,2017-7-13,2016-11-1,0,smb,2016-7-10,0.0,1,paying,1,1.0,2016-4-27,false,0,001b000003Md62f2017-10-04
001b000003I3LyH,2017-10-04,1,2018-03-18,2017-9-17,2017-10-1,0,enterprise,2016-5-11,0.0,1,paying,1,1.0,2016-1-28,false,0,001b000003I3LyH2017-10-04
001b000003MdJHQ,2017-10-04,1,2018-03-18,2017-10-2,2016-11-1,0,smb,2016-8-1,0.0,1,paying,1,1.0,2016-4-27,false,0,001b000003MdJHQ2017-10-04
001b000000Yze26,2017-10-04,1,2018-03-18,2017-9-26,NaN,1,enterprise,2017-4-12,0.0,1,paying,0,0.0,2016-12-12,false,0,001b000000Yze262017-10-04
001b000003NGTXq,2017-10-04,1,2018-03-18,2017-10-4,NaN,1,smb,2016-8-11,0.0,1,paying,0,0.0,2016-5-11,false,0,001b000003NGTXq2017-10-04
001b000001pnVw9,2017-10-04,1,2018-03-18,2017-7-17,2016-4-1,0,smb,2016-02-11,NaN,1,paying,1,1.0,2015-11-11,false,0,001b000001pnVw92017-10-04
001b000003NGgHE,2017-10-04,1,2018-03-18,2017-8-28,NaN,1,smb,2016-8-25,0.0,1,paying,0,0.0,2016-5-25,false,0,001b000003NGgHE2017-10-04
001b000001pneto,2017-10-04,1,2018-03-18,2017-7-15,2017-7-1,0,enterprise,2016-7-2,0.0,1,paying,1,1.0,2015-11-3,false,0,001b000001pneto2017-10-04
001b000001pnkTR,2017-10-04,1,2018-03-18,2017-7-17,2016-9-1,0,smb,2016-02-17,NaN,1,paying,1,1.0,2015-11-17,false,0,001b000001pnkTR2017-10-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
001b000003mXiqy,2017-10-04,1,2018-03-18,2017-9-27,NaN,1,smb,2017-7-26,0.0,1,paying,0,0.0,2017-4-27,false,0,001b000003mXiqy2017-10-04
001b000003qAhl0,2017-10-04,1,2018-03-18,2017-10-3,NaN,1,smb,2017-9-8,0.0,1,paying,0,0.0,2017-6-5,false,0,001b000003qAhl02017-10-04
001b000003nCs6A,2017-10-04,1,2018-03-18,2017-9-22,NaN,0,smb,2017-12-6,0.0,1,poc,0,0.0,2017-8-16,false,0,001b000003nCs6A2017-10-04
001b000003qm2L4,2017-10-04,1,2018-03-18,2017-9-14,2017-9-22,1,smb,2017-9-22,1.0,1,poc,0,1.0,2017-6-20,false,0,001b000003qm2L42017-10-04
001b000003nDnQR,2017-10-04,1,2018-03-18,2017-9-29,NaN,1,enterprise,2017-11-14,0.0,1,poc,0,0.0,2017-8-10,false,0,001b000003nDnQR2017-10-04
001b000003nDphU,2017-10-04,1,2018-03-18,2017-7-30,NaN,0,NaN,2017-08-08,0.0,1,paying,0,0.0,2017-5-8,false,0,001b000003nDphU2017-10-04
001b000003qmcDB,2017-10-04,1,2018-03-18,2017-10-4,NaN,0,smb,2017-12-5,0.0,1,poc,0,0.0,2017-8-31,false,0,001b000003qmcDB2017-10-04
001b000003qmgV1,2017-10-04,1,2018-03-18,2017-10-3,NaN,1,enterprise,2017-11-1,0.0,1,poc,0,0.0,2017-8-1,false,0,001b000003qmgV12017-10-04
001b000003s28vP,2017-10-04,1,2018-03-18,2017-10-3,NaN,1,enterprise,2017-7-3,0.0,1,paying,0,0.0,2017-6-29,false,0,001b000003s28vP2017-10-04
001b000003s29Mp,2017-10-04,1,2018-03-18,2017-9-29,NaN,1,enterprise,2017-10-4,0.0,1,poc,0,0.0,2017-7-3,false,0,001b000003s29Mp2017-10-04
001b000003qnHvF,2017-10-04,1,2018-03-18,2017-9-29,NaN,1,enterprise,2017-10-15,0.0,1,poc,0,0.0,2017-6-27,false,0,001b000003qnHvF2017-10-04
001b000003oIreG,2017-10-04,1,2018-03-18,2017-10-4,NaN,1,enterprise,2017-11-3,0.0,1,poc,0,0.0,2017-8-2,false,0,001b000003oIreG2017-10-04
001b000003nfVdE,2017-10-04,1,2018-03-18,2017-9-28,NaN,1,enterprise,2017-10-31,0.0,1,poc,0,0.0,2017-5-19,false,0,001b000003nfVdE2017-10-04
001b000003nfVtl,2017-10-04,1,2018-03-18,2017-10-4,NaN,1,smb,2017-5-15,0.0,0,paying,0,0.0,2017-5-12,false,0,001b000003nfVtl2017-10-04
001b0000008disE,2017-10-04,1,2018-03-18,2017-10-4,NaN,1,smb,2017-10-23,0.0,1,poc,0,0.0,2017-7-19,false,0,001b0000008disE2017-10-04
001b000000GfnC7,2017-10-04,1,2018-03-18,2017-8-30,NaN,0,enterprise,2016-5-4,0.0,1,paying,1,1.0,2016-2-4,false,0,001b000000GfnC72017-10-04
001b000000FnoxB,2017-10-04,1,2018-03-18,2016-8-7,2016-7-1,0,smb,2016-7-14,1.0,1,poc,0,1.0,2016-3-31,false,0,001b000000FnoxB2017-10-04
001b000000HD2rh,2017-10-04,1,2018-03-18,2017-7-19,2016-1-1,0,smb,2015-09-04,NaN,1,paying,1,1.0,2015-6-4,false,0,001b000000HD2rh2017-10-04
001b000000NuiqD,2017-10-04,1,2018-03-18,2017-9-27,NaN,1,smb,2017-11-1,0.0,1,poc,0,0.0,2017-8-1,false,0,001b000000NuiqD2017-10-04
001b0000003T3TA,2017-10-04,1,2018-03-18,2017-9-22,2017-2-1,0,enterprise,2016-3-1,0.0,0,paying,1,1.0,2016-2-29,false,0,001b0000003T3TA2017-10-04
001b0000003qQeJ,2017-10-04,1,2018-03-18,2017-9-28,NaN,0,smb,2017-1-31,0.0,1,paying,0,0.0,2016-10-27,false,0,001b0000003qQeJ2017-10-04
001b0000007VOae,2017-10-04,1,2018-03-18,2017-9-26,NaN,1,smb,2016-4-2,0.0,0,paying,0,0.0,2016-4-1,false,0,001b0000007VOae2017-10-04
001b0000008cHQd,2017-10-04,1,2018-03-18,2017-7-31,2016-10-1,0,enterprise,2016-6-24,0.0,1,paying,1,1.0,2016-3-24,false,0,001b0000008cHQd2017-10-04
001b000000CkwnY,2017-10-04,1,2018-03-18,2017-9-28,2016-8-1,0,enterprise,2016-7-31,1.0,1,poc,0,1.0,2016-5-31,false,0,001b000000CkwnY2017-10-04
0010J00001oc6R5,2017-10-04,1,2018-03-18,2017-10-4,NaN,0,enterprise,2017-12-27,0.0,1,poc,0,0.0,2017-9-14,false,0,0010J00001oc6R52017-10-04
0010J00001oc6Qv,2017-10-04,1,2018-03-18,2017-9-28,NaN,0,enterprise,2017-12-15,0.0,1,poc,0,0.0,2017-9-15,false,0,0010J00001oc6Qv2017-10-04
0010J00001oc5JA,2017-10-04,1,2018-03-18,2017-10-3,NaN,0,smb,2017-12-18,0.0,1,poc,0,0.0,2017-9-21,false,0,0010J00001oc5JA2017-10-04
0010J00001oc4q3,2017-10-04,1,2018-03-18,2017-9-29,NaN,1,enterprise,2017-12-7,0.0,1,poc,0,0.0,2017-9-6,false,0,0010J00001oc4q32017-10-04
0010J00001oc8BY,2017-10-04,1,2018-03-18,2017-9-28,NaN,0,smb,2017-10-2,0.0,1,paying,0,0.0,2017-9-25,false,0,0010J00001oc8BY2017-10-04
0010J00001oc8DF,2017-10-04,1,2018-03-18,2017-10-11,NaN,0,smb,2017-12-19,0.0,1,poc,0,0.0,2017-9-13,false,0,0010J00001oc8DF2017-10-04

In [221]:
trgt[trgt.id.isin(list(old_less_new))]

,,client_id,recipe_execution_date,last_activity,churn_month,repricing_activated,profile,poc_end_date,churn_in_stage_poc,reached_poc_stage,stage,churn_in_stage_paying,churn_in_stage,account_birth_date,is_deleted,pai_is_deleted,id
pai_account_id,date,,,,,,,,,,,,,,,,
001b000003mZ0Qi,2018-1-29,1,2018-03-18,2018-1-28,NaN,1,enterprise,2017-8-25,0.0,1,paying,0,0.0,2017-5-11,false,0,001b000003mZ0Qi2018-1-29
0010J00001oc8VO,2018-1-29,1,2018-03-18,2018-1-28,NaN,1,smb,2018-1-1,0.0,1,paying,0,0.0,2017-9-28,false,0,0010J00001oc8VO2018-1-29
001b000000NuiqD,2018-1-29,1,2018-03-18,2018-1-24,NaN,1,smb,2017-12-1,0.0,1,paying,0,0.0,2017-8-1,false,0,001b000000NuiqD2018-1-29
001b000003nCs6A,2018-1-29,1,2018-03-18,2018-1-12,NaN,0,smb,2018-3-15,0.0,1,poc,0,0.0,2017-8-16,false,0,001b000003nCs6A2018-1-29
0010J00001ooUjf,2018-1-29,1,2018-03-18,2031-12-23,NaN,1,enterprise,2018-3-10,0.0,1,poc,0,0.0,2017-12-10,false,0,0010J00001ooUjf2018-1-29
0010J00001oqgkS,2018-1-29,1,2018-03-18,2018-3-14,NaN,1,enterprise,2018-3-22,0.0,1,poc,0,0.0,2017-12-22,false,0,0010J00001oqgkS2018-1-29
001b000003nCoYZ,2018-1-29,1,2018-03-18,2018-1-24,NaN,0,smb,2018-4-19,0.0,1,poc,0,0.0,2018-1-20,false,0,001b000003nCoYZ2018-1-29
0010J00001oq1Ks,2018-1-29,1,2018-03-18,2018-1-26,NaN,1,smb,2018-6-2,0.0,1,poc,0,0.0,2017-12-3,false,0,0010J00001oq1Ks2018-1-29
0010J00001oc8DF,2018-1-29,1,2018-03-18,2018-1-22,NaN,1,smb,2017-12-19,0.0,1,paying,0,0.0,2017-9-13,false,0,0010J00001oc8DF2018-1-29
001b000003oIYFz,2018-1-29,1,2018-03-18,2018-1-18,NaN,1,smb,2017-10-15,0.0,1,paying,0,0.0,2017-6-1,false,0,001b000003oIYFz2018-1-29
0010J00001oc8BY,2018-1-29,1,2018-03-18,2018-1-24,NaN,1,smb,2017-10-2,0.0,1,paying,0,0.0,2017-9-25,false,0,0010J00001oc8BY2018-1-29
0010J00001ooUlg,2018-1-29,1,2018-03-18,2018-1-28,NaN,1,smb,2018-5-27,0.0,1,poc,0,0.0,2017-11-27,false,0,0010J00001ooUlg2018-1-29
0010J00001oc4q3,2018-1-29,1,2018-03-18,2017-12-20,2017-12-7,0,enterprise,2017-12-7,1.0,1,poc,0,1.0,2017-9-6,false,0,0010J00001oc4q32018-1-29
001b000000HD2rh,2018-1-29,1,2018-03-18,2018-1-22,2016-1-1,0,smb,2015-09-04,NaN,1,paying,1,1.0,2015-6-4,false,0,001b000000HD2rh2018-1-29
0010J00001oc5JA,2018-1-29,1,2018-03-18,2018-1-26,NaN,1,smb,2018-1-21,0.0,1,paying,0,0.0,2017-9-21,false,0,0010J00001oc5JA2018-1-29
001b000003rbrBc,2018-1-29,1,2018-03-18,2018-1-14,NaN,1,smb,2017-9-29,0.0,1,paying,0,0.0,2017-6-26,false,0,001b000003rbrBc2018-1-29
001b000003rbHuA,2018-1-29,1,2018-03-18,2018-1-25,NaN,1,enterprise,2017-10-11,0.0,0,paying,0,0.0,2017-10-9,false,0,001b000003rbHuA2018-1-29
0010J00001ooV78,2018-1-29,1,2018-03-18,2018-1-8,NaN,1,smb,2018-1-6,0.0,1,paying,0,0.0,2017-10-10,false,0,0010J00001ooV782018-1-29
0010J00001oq3f9,2018-1-29,1,2018-03-18,2018-1-22,NaN,1,enterprise,2018-6-5,0.0,1,poc,0,0.0,2017-12-4,false,0,0010J00001oq3f92018-1-29
0010J00001oc4O9,2018-1-29,1,2018-03-18,2018-1-29,NaN,1,smb,2018-4-26,0.0,1,poc,0,0.0,2017-10-30,false,0,0010J00001oc4O92018-1-29
0010J00001orC6W,2018-1-29,1,2018-03-18,2018-1-27,NaN,1,smb,2018-4-14,0.0,1,poc,0,0.0,2018-1-12,false,0,0010J00001orC6W2018-1-29
001b000003qAhl0,2018-1-29,1,2018-03-18,2018-1-26,NaN,0,smb,2017-9-8,0.0,1,paying,0,0.0,2017-6-5,false,0,001b000003qAhl02018-1-29
001b000003mYGWT,2018-1-29,1,2018-03-18,2017-12-12,2017-11-30,0,enterprise,2017-11-30,1.0,1,poc,0,1.0,2017-4-30,false,0,001b000003mYGWT2018-1-29
001b000003mXnjl,2018-1-29,1,2018-03-18,2017-11-27,2017-10-11,0,smb,2017-9-6,0.0,1,paying,1,1.0,2017-6-1,false,0,001b000003mXnjl2018-1-29
001b000000FnoxB,2018-1-29,1,2018-03-18,2016-8-7,2016-7-1,0,smb,2016-7-14,1.0,1,poc,0,1.0,2016-3-31,false,0,001b000000FnoxB2018-1-29
0010J00001orC7j,2018-1-29,1,2018-03-18,2018-2-3,NaN,1,smb,2018-4-11,0.0,1,poc,0,0.0,2018-1-11,false,0,0010J00001orC7j2018-1-29
0010J00001or0lk,2018-1-29,1,2018-03-18,2018-1-26,NaN,1,smb,2018-4-6,0.0,1,poc,0,0.0,2018-1-6,false,0,0010J00001or0lk2018-1-29
0010J00001opUHM,2018-1-29,1,2018-03-18,2018-2-8,NaN,1,enterprise,2017-11-28,0.0,0,paying,0,0.0,2017-11-28,false,0,0010J00001opUHM2018-1-29
001b000000GfnC7,2018-1-29,1,2018-03-18,2017-8-30,NaN,0,enterprise,2016-5-4,0.0,1,paying,1,1.0,2016-2-4,false,0,001b000000GfnC72018-1-29
0010J00001orEme,2018-1-29,1,2018-03-18,2018-1-17,NaN,1,enterprise,2018-4-12,0.0,1,poc,0,0.0,2018-1-12,false,0,0010J00001orEme2018-1-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
001b000003uqJhb,2017-10-9,1,2018-03-18,2017-10-7,NaN,0,smb,2017-12-28,0.0,1,poc,0,0.0,2017-9-28,false,0,001b000003uqJhb2017-10-9
001b000003uCIsx,2017-10-9,1,2018-03-18,2017-9-28,NaN,1,smb,2017-11-30,0.0,1,poc,0,0.0,2017-8-23,false,0,001b000003uCIsx2017-10-9
001b000003tgOLb,2017-10-9,1,2018-03-18,2017-10-3,NaN,1,enterprise,2017-10-25,0.0,1,poc,0,0.0,2017-7-11,false,0,001b000003tgOLb2017-10-9
001b000003uAHaW,2017-10-9,1,2018-03-18,2017-10-4,NaN,1,enterprise,2017-7-14,0.0,0,paying,0,0.0,2017-7-11,false,0,001b000003uAHaW2017-10-9
001b000003xfj8m,2017-10-9,1,2018-03-18,2017-10-4,NaN,1,smb,2017-9-6,0.0,1,paying,0,0.0,2017-8-31,false,0,001b000003xfj8m2017-10-9
001b000003xbxLc,2017-10-9,1,2018-03-18,2017-9-19,NaN,0,enterprise,2017-12-14,0.0,1,poc,0,0.0,2017-9-13,false,0,001b000003xbxLc2017-10-9
001b000003xfFjr,2017-10-9,1,2018-03-18,2017-10-8,NaN,1,smb,2017-8-31,0.0,0,paying,0,0.0,2017-8-29,false,0,001b000003xfFjr2017-10-9
001b000003xeKAI,2017-10-9,1,2018-03-18,2017-10-6,NaN,0,smb,2017-12-11,0.0,1,poc,0,0.0,2017-9-7,false,0,001b000003xeKAI2017-10-9
001b000003wwrrT,2017-10-9,1,2018-03-18,2017-10-8,NaN,1,smb,2017-8-11,0.0,0,paying,0,0.0,2017-8-9,false,0,001b000003wwrrT2017-10-9
001b000003wxIzl,2017-10-9,1,2018-03-18,2017-10-5,NaN,1,smb,2017-9-18,0.0,1,paying,0,0.0,2017-9-13,false,0,001b000003wxIzl2017-10-9
001b000003wxIch,2017-10-9,1,2018-03-18,2017-10-6,NaN,1,smb,2017-11-24,0.0,1,poc,0,0.0,2017-8-23,false,0,001b000003wxIch2017-10-9
001b000003wvsay,2017-10-9,1,2018-03-18,2017-10-5,NaN,1,enterprise,2017-11-15,0.0,1,poc,0,0.0,2017-8-14,false,0,001b000003wvsay2017-10-9
001b000003wECi5,2017-10-9,1,2018-03-18,2017-10-6,NaN,1,smb,2017-11-17,0.0,1,poc,0,0.0,2017-8-16,false,0,001b000003wECi52017-10-9
001b000000XoteL,2017-10-9,1,2018-03-18,2017-10-19,NaN,1,enterprise,2015-9-2,0.0,1,paying,0,0.0,2015-7-8,false,0,001b000000XoteL2017-10-9
001b000000XDMM0,2017-10-9,1,2018-03-18,2016-11-10,2016-11-1,1,enterprise,2016-6-23,0.0,1,paying,1,1.0,2016-3-23,false,0,001b000000XDMM02017-10-9
001b000000Vr1t8,2017-10-9,1,2018-03-18,2017-10-6,NaN,0,enterprise,2017-9-29,0.0,0,paying,0,0.0,2017-9-26,false,0,001b000000Vr1t82017-10-9
001b000000U1ra9,2017-10-9,1,2018-03-18,2017-10-2,NaN,1,smb,2016-5-1,0.0,0,paying,0,0.0,2016-5-1,false,0,001b000000U1ra92017-10-9
001b000000U1F3o,2017-10-9,1,2018-03-18,2017-9-8,2017-2-1,0,smb,2016-8-12,0.0,1,paying,1,1.0,2016-5-12,false,0,001b000000U1F3o2017-10-9
001b000000S6ErE,2017-10-9,1,2018-03-18,2017-10-4,NaN,1,smb,2017-8-24,0.0,0,paying,0,0.0,2017-8-23,false,0,001b000000S6ErE2017-10-9
001b000000QWlGZ,2017-10-9,1,2018-03-18,2017-7-19,2017-2-1,0,enterprise,2017-2-11,1.0,1,poc,0,1.0,2016-10-11,false,0,001b000000QWlGZ2017-10-9
001b000000PI3ba,2017-10-9,1,2018-03-18,2017-8-29,NaN,1,smb,2016-4-2,0.0,0,paying,0,0.0,2016-4-1,false,0,001b000000PI3ba2017-10-9
001b000000c5VoN,2017-10-9,1,2018-03-18,2017-10-4,NaN,1,enterprise,2017-3-19,0.0,1,paying,0,0.0,2016-10-31,false,0,001b000000c5VoN2017-10-9
001b000000bYVgp,2017-10-9,1,2018-03-18,2017-7-16,2017-8-1,0,smb,2015-7-27,0.0,0,paying,1,1.0,2015-7-26,false,0,001b000000bYVgp2017-10-9
001b000000bQPWF,2017-10-9,1,2018-03-18,2017-9-26,NaN,1,smb,2016-5-2,0.0,0,paying,0,0.0,2016-5-1,false,0,001b000000bQPWF2017-10-9
001b000000bPoV1,2017-10-9,1,2018-03-18,2017-9-13,2016-10-1,0,enterprise,2016-02-19,NaN,1,paying,1,1.0,2015-11-19,false,0,001b000000bPoV12017-10-9
001b000000a88xI,2017-10-9,1,2018-03-18,2017-7-12,2016-3-1,0,smb,2015-12-29,NaN,1,paying,1,1.0,2015-9-29,false,0,001b000000a88xI2017-10-9
001b000000a7QJc,2017-10-9,1,2018-03-18,2017-10-2,2016-9-1,0,enterprise,2016-9-21,1.0,1,poc,0,1.0,2016-7-21,false,0,001b000000a7QJc2017-10-9
001b000000a7BUf,2017-10-9,1,2018-03-18,2017-10-4,2016-12-1,0,smb,2015-12-2,0.0,1,paying,1,1.0,2015-7-15,false,0,001b000000a7BUf2017-10-9
001b000000Yze26,2017-10-9,1,2018-03-18,2017-9-26,NaN,1,enterprise,2017-4-12,0.0,1,paying,0,0.0,2016-12-12,false,0,001b000000Yze262017-10-9
001b000003NHFmc,2017-11-27,1,2018-03-18,2017-10-2,2016-9-1,0,enterprise,2016-8-15,1.0,1,poc,0,1.0,2016-5-15,false,0,001b000003NHFmc2017-11-27

In [56]:
t = pd.Series(sorted(trgt[trgt.id.isin(list(diff_by_id))].reset_index().date.unique()))

Bingo!

# Old stuff

In [4]:
z1 = 'FEEDVISOR_shonot_2018-06-04_cleaned_pai_snapshot/'
z2 = 'FEEDVISOR_shonot_2018-06-12_backup_of_pre_stich_data/'
z3 = 'FEEDVISOR_shonot_2018-06-12_cleaned_snapshot_gap_start_from_2018-06-04/'
z4 = 'FEEDVISOR_shonot_2018-09-04_new_feedvisor_prestich/'

In [5]:
z1_trgt = z1 + 'cleaned_pai_snapshot_c1_d2018-06-04_target.csv'
z1_acct = z1 + 'cleaned_pai_snapshot_c1_d2018-06-04_account.csv'

z2_trgt = z2 + 'FEEDVISOR%2Fcleaned_target_FEEDVISOR.csv'
z2_acct = z2 + 'FEEDVISOR%2Fcleaned_account_FEEDVISOR.csv'
z2_acct_2 = z2 + 'processed_pai_snapshot_c6_d2018-09-12_account.csv'

z3_trgt = z3 + 'FEEDVISOR%2Fcleaned_target_FEEDVISOR.csv'
z3_acct = z3 + 'FEEDVISOR%2Fcleaned_account_FEEDVISOR.csv'

z4_trgt = z4 + 'pre_stitch_cleaned_target.csv'
z4_acct = z4 + 'pre_stitch_cleaned_account.csv'

In [7]:
trgt_files = [z1_trgt, z2_trgt, z3_trgt, z4_trgt]
acct_files = [z1_acct, z2_acct, z3_acct, z4_acct]

In [14]:
x1[x1.date.str.len() == 6]

,recipe_execution_date,date,client_id,pai_account_id,last_activity,churn_month,repricing_activated,profile,poc_end_date,stage,churn_in_stage,account_birth_date,reached_poc_stage,churn_in_stage_poc,churn_in_stage_paying,is_deleted,source,pai_is_deleted
499506,2018-09-02,#NAME?,1,NaN,NaN,NaN,1,NaN,NaN,poc,0.0,NaN,1,0.0,0,NaN,3,1.0

In [20]:
x1.date = x1.date.apply(lambda x:x[:10] if len(x) == 19 else x)
x2.date = x2.date.apply(lambda x:x[:10] if len(x) == 19 else x)

In [23]:
x1['id'] = x1['date'] + x1['pai_account_id']
x2['id'] = x2['date'] + x2['pai_account_id']

In [25]:
acct['id'] = acct['date'] + acct['pai_account_id']
trgt['id'] = trgt['date'] + trgt['pai_account_id']

In [26]:
missing_trgt = set(x1.id.values) - set(trgt.id.values)

In [32]:
missing_df = x1[x1.id.isin(missing_trgt)]

In [25]:
trgt_dates = []
for df in trgt_dfs:
    df = df.dropna(subset=['date'])
    df['id'] = df['date'] + df['pai_account_id']
    trgt_dates.append(df['id'].values)

/Users/joshfriedlander/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [34]:
flat_list = set([item for sublist in trgt_dates for item in sublist])

In [36]:
len(flat_list)

732843

In [37]:
acct_dates = []
for df in acct_dfs:
    df = df.dropna(subset=['date'])
    df['id'] = df['date'] + df['pai_account_id']
    acct_dates.append(df['id'].values)

/Users/joshfriedlander/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [38]:
flat_list_acct = set([item for sublist in acct_dates for item in sublist])

In [39]:
len(flat_list_acct)

732857

In [45]:
missing = set(flat_list_acct) - set(acct.id.values)

In [18]:
all_null_cols = ['x2nd_repricer_of_products_repriced']
pointless_cols = ['client_id', 'recipe_execution_date', 'pai_is_deleted']
cols_to_drop = all_null_cols + pointless_cols

In [13]:
support['gap'] = (pd.to_datetime(support.ticket_solved_time) - pd.to_datetime(support.ticket_open_time)).dt.days

In [15]:
support = support[[ 'pai_account_id', 'date', 'ticket_id', 'agent_wait_time', 'days_open', 'last_modified_date', 
              'priority', 'profile', 'reply time', 'requester_wait_time', 'resolution_time', 'severity', 'stage', 
              'status', 'ticket_open_time', 'ticket_solved_time', 'ticket_type', 'time_zone_region']]

In [53]:
cols_to_normalize = ['number_of_builds', 'number_of_successful_builds', 'sum_of_dashboardload_events', 
                     'unique_number_of_cubes_in_build', 'unique_viewers']

In [11]:
df = usage[cols_to_normalize]

In [13]:
normalized_usage = (df - df.mean()) / df.std()
normalized_usage.head()

,number_of_builds,number_of_successful_builds,sum_of_dashboardload_events,unique_number_of_cubes_in_build,unique_viewers
0,-0.307125,-0.298975,NaN,-0.102767,-0.162562
1,-0.307125,-0.298975,NaN,-0.102767,-0.162562
2,0.691544,0.408378,-0.195866,-0.102767,-0.162562
3,0.691544,0.408378,-0.195866,-0.102767,-0.162562
4,0.691544,0.408378,-0.195866,-0.102767,-0.162562

In [16]:
normalized_df=(df-df.min())/(df.max()-df.min())
normalized_df.head()

,number_of_builds,number_of_successful_builds,sum_of_dashboardload_events,unique_number_of_cubes_in_build,unique_viewers
0,0.000521,0.000261,NaN,0.004098,0.000128
1,0.000521,0.000261,NaN,0.004098,0.000128
2,0.043687,0.029132,0.008093,0.004098,0.000128
3,0.043687,0.029132,0.008093,0.004098,0.000128
4,0.043687,0.029132,0.008093,0.004098,0.000128

In [2]:
def table_analyser(df):
    data = []
    for col in list(df):
        data.append([float((df[col].isna().sum() / df[col].shape[0]) * 100), df[col].nunique()])
    return pd.DataFrame(data, index=list(df), columns=['NaNs', 'Uniques'])#, dtype={'NaNs':int})

In [40]:
df=pd.read_clipboard(sep='\s\s+', engine='python'); df.head()

     Number           String      Aut
0  [12, 13]  [hi are, ho to]    ppppp
1        34              How    qqqqq
2        35              are  wwwwwww